<a href="https://colab.research.google.com/github/suhanasuneer/Data-Science-lab/blob/main/array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [18]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
x = np.arange(25).reshape(5,5)
print(x)
print(x.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)


In [10]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [13]:
a=np.array([1,2,3])
print(type(a))
print(a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


In [17]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0])
print(b)

(2, 3)
1 2 4
[[1 2 3]
 [4 5 6]]
